#DESC	1.2 * DESCRIPTOR INFORMATION ***********************
*
*	Dataset Type and Format:
*
DSRC	EXP
BSEQ	BIG
IKKF	CPLX
XTYP	IDX
YTYP	NODATA
ZTYP	NODATA
*
*	Item Formats:
*
IRFMT	D
IIFMT	D
*
*	Data Ranges and Resolutions:
*
XPTS	367
XMIN	0
XWID	2928
*
*	Documentational Text:
*
TITL	'DEER_RRM34_388_475_MAP_54uM_d2_6us_75scs_spec.DSC'
IRNAM	'Intensity'
IINAM	'Intensity'
XNAM	'Time'
IRUNI	''
IIUNI	''
XUNI	'ns'
*
************************************************************
*
#SPL	1.2 * STANDARD PARAMETER LAYER
*
OPER    epruser
DATE    12/08/16
TIME    08:33:49
CMNT    
SAMP    
SFOR    
STAG    C
EXPT    PLS
OXS1    TADC
AXS1    B0VL
AXS2    NONE
AXS3    
MWPW    0.000
A1CT    1.22885
B0VL    1.22885
A1SW    0.02
MWFQ    0.0
AVGS    75
*
************************************************************
*
#DSL	1.0 * DEVICE SPECIFIC LAYER
*
.DVC     acqStart, 1.0
.DVC     cwBridge, 1.0
AcqFineTuning      Never
AcqScanFTuning     Off
AcqSliceFTuning    Off
Power              0.000 mW
PowerAtten         60 dB
.DVC     endor, 1.0
EIEENDORFreq       14.9021800 MHz/3.5 kG
EIEIsotope         H1
EIERFSweepDir      Same
EIEStaticField     12140.000 G
EIEStaticRF        38.000 MHz
ENDORType          EIF
RF1Atten           60.000 dB
RF1FreqPos         38.000 MHz
RF1StartFreq       38.000 MHz
RF1SweepWidth      30.000 MHz
RF2Atten           60.000 dB
RF2FreqPos         38.000 MHz
RF2StartFreq       38.000 MHz
RF2SweepWidth      30.000 MHz
RFSrcMixing        Add
SumAtten           10.000 dB
SumAttenStart      10.000 dB
SumAttenWidth      70.000 dB
.DVC     fieldCtrl, 1.0
AllegroMode        False
CenterField        12288.50 G
Delay              0.0 s
FieldFlyback       On
FieldPosition      12288.500 G
FieldWait          Wait LED off
GFactor            2.000000
MeasuringHall      False
SetToSampleG       False
StaticFieldMon     12451.500 G
SweepDirection     Up
SweepWidth         200.0 G
WidthTM            200.0 G
.DVC     freqCounter, 1.0
FrequencyMon       0.0 GHz
QMonitBridge       Off
.DVC     ftBridge, 1.0
.DVC     ftEpr, 1.0
AutoTimeOut        True
AveragesPerScan    25
ELDORFreqStart     9.300000 GHz
ELDORFreqWidth     0.700000 GHz
FTAcqModeSlct      Run from PulseSPEL
FieldIsStatic      False
GradIntPulse       False
GrdEnable          False
LastXAxis          Time
LastYAxis          Magnetic Field
PCycleAllowed      True
PCycleOn           False
PPExtTrg           False
PPExtTrgSlope      Rising
PlsSPELEXPSlct     DEER
PlsSPELGlbTxt      \

